//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WvW_Toolbox.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WvW_Toolbox.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///
        ///    {
        ///      &quot;id&quot;: 1001,
        ///      &quot;name&quot;: &quot;Anvil Rock&quot;,
        ///      &quot;population&quot;: &quot;Medium&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 1002,
        ///      &quot;name&quot;: &quot;Borlis Pass&quot;,
        ///      &quot;population&quot;: &quot;Medium&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 1003,
        ///      &quot;name&quot;: &quot;Yak&apos;s Bend&quot;,
        ///      &quot;population&quot;: &quot;Full&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 1004,
        ///      &quot;name&quot;: &quot;Henge of Denravi&quot;,
        ///      &quot;population&quot;: &quot;Medium&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 1005,
        ///      &quot;name&quot;: &quot;Maguuma&quot;,
        ///      &quot;population&quot;: &quot;Full&quot;
        ///    },
        ///    {
        ///      &quot;id&quot;: 1006,
        ///      &quot;name&quot;: &quot;S [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AllWorldsJson {
            get {
                return ResourceManager.GetString("AllWorldsJson", resourceCulture);
            }
        }
    }
}
